### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by zgrimshell** [zgrimshell/scratch-website-pape#3]
What are pros and cons for implementing CSS directly into HTML file? I think at least pros is speed of website rendering and cons is bigger html file?

**Comment by ghost** [comment]
I think we should definitely put CSS in a separate file, That way we have separation of content and presentation, content is in one file and presentation of that content is in another file. We can later alter the visuals of site just by editing that CSS file or even completely change the appearance of it by linking HTML document to another CSS file.

**Comment by zgrimshell** [comment]
Yep, agree on that. CSS is now separate. :smile:
